site_name: RetroBioCat 2
nav:
  - Home: index.md
  - Expanders - single step retrosynthesis: single_step_retrosynthesis.md
  - The Data Model: data_model.md
  - Multi step retrosynthesis: multi_step_retrosynthesis.md
theme: readthedocs

